variables:
  S3_BUCKET_NAME: "www.tippmate.de"

stages:
  - build
  - deploy_production


build:
  image: ruby:latest
  script:
    - bundle install
    - jekyll build
  artifacts:
    paths:
      - _site

deploy_production:
  environment: production
  image: python:latest
  script:
    - ls -a
  # - pip install awscli
  # - aws s3 cp ./_site s3://$S3_BUCKET_NAME/ --recursive
  only:
  - master